@echo off
echo Parando todos os processos Node.js...
taskkill /f /im node.exe >nul 2>&1

echo Aguardando 2 segundos...
timeout /t 2 /nobreak >nul

echo Verificando se a porta 4000 esta livre...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :4000') do (
    echo Matando processo %%a que esta usando a porta 4000...
    taskkill /f /pid %%a >nul 2>&1
)

echo Aguardando mais 1 segundo...
timeout /t 1 /nobreak >nul

echo Iniciando o bot...
node index.js
