name: Private Receiver tests

on:
  push: {}
  pull_request: {}

jobs:
  private-receiver-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Start private receiver (background, capture logs)
        run: |
          # start server and redirect stdout/stderr to file
          node ./examples/private-receiver/server.js > receiver.log 2>&1 &
          PID=$!
          echo "started pid=$PID"
          echo $PID > receiver.pid
          # wait for a healthy HTTP 200 at / (up to ~20s)
          for i in $(seq 1 20); do
            HTTP_CODE=$(curl -sS -o /dev/null -w "%{http_code}" http://localhost:3001/ || true)
            if [ "$HTTP_CODE" = "200" ]; then echo "server up (attempt $i)" && break; fi
            sleep 1
          done
          # export PID and log path for later steps
          echo "RECEIVER_PID=$PID" >> $GITHUB_ENV
          echo "RECEIVER_LOG=receiver.log" >> $GITHUB_ENV
      - name: Run tests
        run: npm run test:private-receiver
      - name: Show receiver log on failure
        if: failure()
        run: |
          echo "===== receiver.log (job failed) ====="
          cat receiver.log || true
      - name: Stop private receiver
        if: always()
        run: |
          if [ -f receiver.pid ]; then PID=$(cat receiver.pid); kill $PID || true; fi

